{
    "room":                     "Crawti's Party",
    "author":                   "Crawti",
    "icon":                     "http://i.imgur.com/sVHVk2S.png",
    "css":                      "https://raw.githubusercontent.com/Crawti/plugdj/master/theme.ccs",
    "rules": {
        "allowAutorespond":     true,
        "allowAutowoot":        true,
        "allowAutojoin":        false,
        "allowAutograb":        true,
        "allowSmartVote":       true,
        "allowEmotes":          true,
        "allowShowingMehs":     true,
        "forceSmartVote":       false
    },
    "ccc": {
        "admin":                "#000080",
        "ambassador":           "#008000",
        "host":                 "#FF0000",
        "cohost":               "#FFA500",
        "manager":              "#FF00FF",
        "bouncer":              "#800000",
        "rdj":                  "#00FFFF",
        "subscriber":           "#FFFF00",
        "silversubscriber":     "#8B8B00",
        "friend":               "#00EE76",
        "user":                 "#EEEED1"
    },
    "images": {
        "background":           'http://i.imgur.com/3bbSwm2.jpg",
        "playback":             "http://i.imgur.com/KyExkDf.png",
        "admin":                "https://cdn.radiant.dj/rcs/icons/radiant/admin.png",
        "ambassador":           "https://cdn.radiant.dj/rcs/icons/radiant/ambassador.png",
        "host":                 "https://cdn.radiant.dj/rcs/icons/radiant/host.png",
        "cohost":               "https://cdn.radiant.dj/rcs/icons/radiant/cohost.png",
        "manager":              "https://cdn.radiant.dj/rcs/icons/radiant/manager.png",
        "bouncer":              "https://cdn.radiant.dj/rcs/icons/radiant/bouncer.png",
        "rdj":                  "https://cdn.radiant.dj/rcs/icons/radiant/residentdj.png",
        "subscriber":           "https://vgy.me/Ic53MB.png',
        "silversubscriber":     "https://vgy.me/ZPcDCs.png",
    },
    "emotes": {
    "Crawti": "https://media.giphy.com/media/8OUdE03f3Nauc/giphy_s.gif",
    "Axxi ♔": "https://s-media-cache-ak0.pinimg.com/236x/78/10/2c/78102c2cd3e75b0d1fbc33e02807e346.jpg,
    "summer4ever": "http://cdn.osxdaily.com/wp-content/uploads/2013/07/dancing-banana.gif",
    "FireForry": "https://media.giphy.com/media/850z0YBGF1RYs/giphy.gif",
    "Martin Kuta": "http://data.whicdn.com/images/26306887/large.gif",
    "SpaceMan Offical™": "http://planetadelibrosmexico.com/wp-content/uploads/2015/05/04-astronauta.gif",
    "♫CP-BØT♫": "https://telegram.org/file/811140058/2/7GzMJk4Ij54/a1649c56fa9f805828",
    "Aɪwʏ ⚔": "http://37.media.tumblr.com/tumblr_lj95h9q5EK1qh3j4zo1_500.gif",
    "Dεεנคү": "http://www.gazeta.mazury.pl/wp-content/uploads/2013/10/dj.gif",
    "fiflefufle": "http://i1344.photobucket.com/albums/p642/pacman8myghosts/48straighthoursofvidya_zps7fd7c587.gif",
    "Firemistr": "https://media4.giphy.com/media/8QdHDION7cJIQ/200_s.gif",
    "HornetCZ": "http://www.topbest.ph/blog/wp-content/uploads/2014/12/japanese-honey-bees.gif",
    "Lauraツ": "https://www.askideas.com/media/14/Smile-Countdown-Gif-Picture.gif",
    "✧AϯϮเ༻✧ シ": "http://orig15.deviantart.net/31a9/f/2015/239/0/4/sollux_shrug_gif__horrible_preview__by_italianatti-d97eonw.gif,
    "I Love Bass-Boost": "https://s-media-cache-ak0.pinimg.com/originals/14/57/6d/14576d4d53807c5c9c4f3cc5cbed1c38.jpg",
    "JBoxCZ": "http://vignette2.wikia.nocookie.net/crazybonespedia/images/c/c2/Jbox12.png/revision/latest?cb=20130914042959",
    "Kubulík": "http://www.libornovotny.cz/JAR/JAR_button.gif",
    "lolacolacz": "http://www.picgifs.com/graphics/c/coca-cola/graphics-coca-cola-777237.gif",
    "PAIA_CZ": "http://i.imgur.com/NLKaVrD.gif",
    }
}
